name: Build All
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchains
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu \
            gcc-arm-linux-gnueabihf \
            gcc-x86-64-linux-gnu \
            gcc-riscv64-linux-gnu \
            device-tree-compiler
      - name: Build all
        run: tools/scripts/makeall